services:
  postgres:
    image: postgres:15-alpine
    container_name: journal-postgres
    environment:
      POSTGRES_DB: journal_db
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: journal-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: